language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux

before_install:
- sudo chmod 777 ./travis-scripts/*
- ./travis-scripts/dependencies.sh
- pip install --user cpp-coveralls
script:
- ./travis-scripts/build.sh
after_success:
  - coveralls --exclude tests --gcov-options '\-lp'

branches:
  only:
  - master