language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux

before_install:
- sudo chmod 777 ./travis-scripts/*
- ./travis-scripts/dependencies.sh
script:
- ./travis-scripts/build.sh

branches:
  only:
  - master